[license_info]
license = "Apache License, Version 2.0"
LicensePath = "LICENSE"

[music]
background = "audio/main-music.wav"
chompEffect = "audio/chomp.wav"
laserBeamEffect = "audio/laser.wav"
ghostReviveEffect = "audio/ghost_revive.wav"
xpSpeedUpEffect = "audio/xpwroom.wav"

[data]
MatrixRenderingFile = "data/ascii-art.txt"