[license_info]
license = "Apache License, Version 2.0"
LicensePath = "LICENSE"

[music]
background = "audio/main-music.wav"
victory = "audio/victory.wav"
lose = "audio/losing.wav"
chompEffect = "audio/chomp.wav"
laserBeamEffect = "audio/laser.wav"
ghostReviveEffect = "audio/ghost_revive.wav"
xpSpeedUpEffect = "audio/xpwroom.wav"
magnetPickupEffect = "audio/magnet-pickup.wav"
magicEffect = "audio/special1.wav"
magnetLosingEffect = "audio/magnet-losing.wav"
powerUpEffect = "audio/chime.wav"
invisibleEffect = "audio/invisible.wav"
shopBackground = "audio/shop-music.wav"
shopBuySuccess = "audio/buy-success.wav"
shopBuyError = "audio/buy-error.wav"
shopHistoryBrowse = "audio/history-nav.wav"
homeBackground = "audio/home_music.wav"
authBackground = "audio/auth_music.wav"
authIntro = "audio/auth_intro.wav"
settingsBackground = "audio/settings_music.wav"

[data]
MatrixRenderingFile = "data/ascii-art.txt"

[version]
SectorEightVersion = "Sector Eight 1.0.0 Beta Development"

[performance]
FPS = 60
VSync = true

[font]
fontList = [
    "Cascadia Mono",
    "Cascadia Code",
    "Courier New",
]
emojiFont = "Segoe UI Emoji"
