[license_info]
license = "Apache License, Version 2.0"
LicensePath = "LICENSE"

[music]
background = "audio/main-music.wav"
victory = "audio/victory.wav"
lose = "audio/losing.wav"
chompEffect = "audio/chomp.wav"
laserBeamEffect = "audio/laser.wav"
ghostReviveEffect = "audio/ghost_revive.wav"
xpSpeedUpEffect = "audio/xpwroom.wav"
magnetPickupEffect = "audio/magnet-pickup.wav"
magicEffect = "audio/special1.wav"
magnetLosingEffect = "audio/magnet-losing.wav"
powerUpEffect =  "audio/chime.wav"
invisibleEffect = "audio/invisible.wav"

[data]
MatrixRenderingFile = "data/ascii-art.txt"

[font]
fontList = ['Cascadia Mono', 'Cascadia Code','Courier New'] # Font fallback sequence